# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import msg_pb2 as msg__pb2


class FormatDataStub(object):
    """定义服务，下面定义的这种为最简单的rpc服务，客户端发起请求，服务端返回结果
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_roi_from_bytes = channel.unary_unary(
                '/ShipRoi_grpc.FormatData/get_roi_from_bytes',
                request_serializer=msg__pb2.request_bytes.SerializeToString,
                response_deserializer=msg__pb2.actionresponse.FromString,
                )
        self.get_roi_from_path = channel.unary_unary(
                '/ShipRoi_grpc.FormatData/get_roi_from_path',
                request_serializer=msg__pb2.request_path.SerializeToString,
                response_deserializer=msg__pb2.actionresponse.FromString,
                )


class FormatDataServicer(object):
    """定义服务，下面定义的这种为最简单的rpc服务，客户端发起请求，服务端返回结果
    """

    def get_roi_from_bytes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_roi_from_path(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FormatDataServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_roi_from_bytes': grpc.unary_unary_rpc_method_handler(
                    servicer.get_roi_from_bytes,
                    request_deserializer=msg__pb2.request_bytes.FromString,
                    response_serializer=msg__pb2.actionresponse.SerializeToString,
            ),
            'get_roi_from_path': grpc.unary_unary_rpc_method_handler(
                    servicer.get_roi_from_path,
                    request_deserializer=msg__pb2.request_path.FromString,
                    response_serializer=msg__pb2.actionresponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ShipRoi_grpc.FormatData', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FormatData(object):
    """定义服务，下面定义的这种为最简单的rpc服务，客户端发起请求，服务端返回结果
    """

    @staticmethod
    def get_roi_from_bytes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ShipRoi_grpc.FormatData/get_roi_from_bytes',
            msg__pb2.request_bytes.SerializeToString,
            msg__pb2.actionresponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_roi_from_path(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ShipRoi_grpc.FormatData/get_roi_from_path',
            msg__pb2.request_path.SerializeToString,
            msg__pb2.actionresponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
