# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tmsg.proto\x12\x0cShipRoi_grpc\"U\n\rrequest_bytes\x12\x0c\n\x04mode\x18\x01 \x01(\t\x12\r\n\x05image\x18\x02 \x01(\x0c\x12\x13\n\x0bimage_shape\x18\x03 \x03(\x03\x12\x12\n\nconfidence\x18\x04 \x01(\x01\"?\n\x0crequest_path\x12\x0c\n\x04mode\x18\x01 \x01(\x05\x12\r\n\x05image\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x01\"2\n\x0e\x61\x63tionresponse\x12 \n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x12.ShipRoi_grpc.DATA\"5\n\x04\x44\x41TA\x12\x0b\n\x03ROI\x18\x01 \x03(\x05\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x01\x32\xb0\x01\n\nFormatData\x12Q\n\x12get_roi_from_bytes\x12\x1b.ShipRoi_grpc.request_bytes\x1a\x1c.ShipRoi_grpc.actionresponse\"\x00\x12O\n\x11get_roi_from_path\x12\x1a.ShipRoi_grpc.request_path\x1a\x1c.ShipRoi_grpc.actionresponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'msg_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUEST_BYTES']._serialized_start=27
  _globals['_REQUEST_BYTES']._serialized_end=112
  _globals['_REQUEST_PATH']._serialized_start=114
  _globals['_REQUEST_PATH']._serialized_end=177
  _globals['_ACTIONRESPONSE']._serialized_start=179
  _globals['_ACTIONRESPONSE']._serialized_end=229
  _globals['_DATA']._serialized_start=231
  _globals['_DATA']._serialized_end=284
  _globals['_FORMATDATA']._serialized_start=287
  _globals['_FORMATDATA']._serialized_end=463
# @@protoc_insertion_point(module_scope)
